version: '3.5'

services:
  back:
    image: back
    volumes:
      - ./logs.txt:/backend-example-docker-master/logs.txt
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=supersecret
      - DB_NAME=postgres
      - DB_HOST=db

  front:
    image: front
    environment:
      - API_URL=/api

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=supersecret 

  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
