version: '3.5'

services:
  backend:
    image: back
    ports: 
      - 8000:8000
    volumes:
      - ./logs.txt:/backend-example-docker-master/logs.txt
    environment:
      - REDIS=redis

  front:
    image: front
    ports:
      - 5000:5000

  redis:
    image: redis:latest
